
author: Tobias Schulz-Hess
markdown: kramdown
theme: minima

minima:
  social_links:
    twitter: ToBe_HH
    github: tobehh
    stackoverflow: "tobe-hh"
    # flickr: jekyll
    instagram: schulzhess
    linkedin: schulz-hess

    mastodon:
      - username: ToBe_HH
        instance: norden.social

    youtube_channel: UCbtMFRDhXJy5ThobWxt3Ogw
    youtube_channel_name: Tobias Schulz-Hess
  skin: solarized
twitter:
  username: ToBe_HH

# 2.5.1 minima schema:
twitter_username: ToBe_HH
github_username: tobehh
stackoverflow_username: "tobe-hh"
instagram_username: schulzhess
linkedin_username: schulzhess

mastodon:
  - username: ToBe_HH
    instance: norden.social